# This is a basic workflow to help you get started with Actions

name: running acceptance test
# Controls when the workflow will run
#    branches: [ main LTS ]
on:
  # Triggers the workflow on push or pull request events but only for the 3.4.0 branch
  push:
    paths-ignore:
      - 'docs/**'
#      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      message:
        description: 'running acceptance test'     
        required: true

env:
  commitmsg: ${{ github.event.head_commit.message }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  acceptancetest_0:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test testIO_AcceptanceProcOutputIOTests testIO_UnitProcOutputIOTests test_hepmc_decay test_lhe_none_decay test_madspin_spin_only
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py testIO_AcceptanceProcOutputIOTests testIO_UnitProcOutputIOTests test_hepmc_decay test_lhe_none_decay test_madspin_spin_only -pA -t0



  acceptancetest_1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_config test_draw test_generate test_import_model test_check_generate_optimize
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_config test_draw test_generate test_import_model test_check_generate_optimize -pA -t0



  acceptancetest_2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_complex_mass_SA test_custom_propa test_define_order test_import_banner_command test_invalid_operations_for_add
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_complex_mass_SA test_custom_propa test_define_order test_import_banner_command test_invalid_operations_for_add -pA -t0



  acceptancetest_3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_invalid_operations_for_generate test_invalid_operations_for_output test_leshouche_sextet_diquarks test_load_feynman test_madevent_decay_chain
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_invalid_operations_for_generate test_invalid_operations_for_output test_leshouche_sextet_diquarks test_load_feynman test_madevent_decay_chain -pA -t0



  acceptancetest_4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_madevent_subproc_group test_madevent_subproc_group_decay_chain test_madevent_subproc_group_symmetry test_madevent_triplet_diquarks test_madevent_ufo_aloha
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_madevent_subproc_group test_madevent_subproc_group_decay_chain test_madevent_subproc_group_symmetry test_madevent_triplet_diquarks test_madevent_ufo_aloha -pA -t0



  acceptancetest_5:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_output_madevent_directory test_output_standalone_directory test_pythia8_output test_read_madgraph4_proc_card test_save_load
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_output_madevent_directory test_output_standalone_directory test_pythia8_output test_read_madgraph4_proc_card test_save_load -pA -t0



  acceptancetest_6:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_standalone_cpp test_standalone_cpp_output test_standalone_cpp_output_consistency test_ufo_aloha test_ufo_standard_sm
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_standalone_cpp test_standalone_cpp_output test_standalone_cpp_output_consistency test_ufo_aloha test_ufo_standard_sm -pA -t0



  acceptancetest_7:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_ungroup_decay test_v4_heft test_loop_improved_reweighting test_mass_reweighting test_nlo_output2
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_ungroup_decay test_v4_heft test_loop_improved_reweighting test_mass_reweighting test_nlo_output2 -pA -t0



  acceptancetest_8:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_nlo_reweighting test_oneloop_reweighting test_scan_reweighting test_complex_mass_scheme test_creating_matched_plot
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_nlo_reweighting test_oneloop_reweighting test_scan_reweighting test_complex_mass_scheme test_creating_matched_plot -pA -t0



  acceptancetest_9:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_customised_madevent_via_run_card test_e_e_collision test_e_p_collision test_eft_running test_eva_collision
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_customised_madevent_via_run_card test_e_e_collision test_e_p_collision test_eft_running test_eva_collision -pA -t0



  acceptancetest_10:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_group_subprocess test_madevent_ptj_bias test_madspin_gridpack test_width_computation test_width_nlocomputation
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_group_subprocess test_madevent_ptj_bias test_madspin_gridpack test_width_computation test_width_nlocomputation -pA -t0



  acceptancetest_11:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_width_scan test_run_fromP test_add_time_of_flight test_contur_from_file test_decay_width_nlo_model
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_width_scan test_run_fromP test_add_time_of_flight test_contur_from_file test_decay_width_nlo_model -pA -t0



  acceptancetest_12:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_generation_from_file_1 test_rivet_from_file test_w_production_with_ms_decay test_mw_wjjproduction test_mw_wproduction
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_generation_from_file_1 test_rivet_from_file test_w_production_with_ms_decay test_mw_wjjproduction test_mw_wproduction -pA -t0



  acceptancetest_13:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_tt_semi test_zh test_mssm_equivalence test_sm_equivalence test_all
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_tt_semi test_zh test_mssm_equivalence test_sm_equivalence test_all -pA -t0



  acceptancetest_14:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test testIO_TIR_output test_ML_check_brs_gd_gd test_ML_check_cms_aem_emvevex test_ML_check_cms_al_lvlvlx_LO test_ML_check_full_epem_ttx
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py testIO_TIR_output test_ML_check_brs_gd_gd test_ML_check_cms_aem_emvevex test_ML_check_cms_al_lvlvlx_LO test_ML_check_full_epem_ttx -pA -t0



  acceptancetest_15:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_ML_check_profile_epem_ttx test_ML_check_timing_epem_ttx testIO_MatchBoxOutput testIO_check_html_long_process_strings test_amcantlo_script
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_ML_check_profile_epem_ttx test_ML_check_timing_epem_ttx testIO_MatchBoxOutput testIO_check_html_long_process_strings test_amcantlo_script -pA -t0



  acceptancetest_16:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_amcatnlo_from_file test_calculate_xsect_lo test_calculate_xsect_nlo test_check_singletop_fastjet test_eft_running_nlo
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_amcatnlo_from_file test_calculate_xsect_lo test_calculate_xsect_nlo test_check_singletop_fastjet test_eft_running_nlo -pA -t0



  acceptancetest_17:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_gen_evt_onlygen test_generate_eett_lo_emela_clusterpath test_generate_eett_nlo_emela_bs test_generate_eett_nlo_qcd_noisr test_generate_eeww_nlo_emela_noph
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_gen_evt_onlygen test_generate_eett_lo_emela_clusterpath test_generate_eett_nlo_emela_bs test_generate_eett_nlo_qcd_noisr test_generate_eeww_nlo_emela_noph -pA -t0



  acceptancetest_18:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_generate_eeww_nlo_emela_wph test_generate_events_lo_hw6_stdhep test_generate_events_lo_py6_stdhep test_generate_events_nlo_hw6_split test_generate_taggedph_nloew
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_generate_eeww_nlo_emela_wph test_generate_events_lo_hw6_stdhep test_generate_events_lo_py6_stdhep test_generate_events_nlo_hw6_split test_generate_taggedph_nloew -pA -t0



  acceptancetest_19:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_madspin_LOonly test_madspin_ON_and_onshell_atNLO test_raise_invalid_path_hwpp test_raise_invalid_path_py8 test_split_evt_gen
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py test_madspin_LOonly test_madspin_ON_and_onshell_atNLO test_raise_invalid_path_hwpp test_raise_invalid_path_py8 test_split_evt_gen -pA -t0



  acceptancetest_20:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test testIO_gnuplot_histo_output
        run: |
            cd $GITHUB_WORKSPACE
            ./tests/test_manager.py testIO_gnuplot_histo_output -pA -t0


